-- 03_create_tables.sql
-- Migration to create remaining tables used by the app

-- Courses table (mba_courses)
CREATE TABLE public.mba_courses (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE
);

-- Questions bank table
CREATE TABLE public.questions_bank (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  course_id integer NOT NULL REFERENCES public.mba_courses(id) ON DELETE CASCADE,
  title text NOT NULL,
  description text,
  file_url text,
  file_type text,
  created_at timestamp with time zone DEFAULT now()
);

-- Enable Row Level Security on questions_bank (optional – you can adjust policies later)
ALTER TABLE public.questions_bank ENABLE ROW LEVEL SECURITY;

-- Policies for questions_bank
CREATE POLICY "questions select" ON public.questions_bank FOR SELECT USING (true);
CREATE POLICY "questions modify" ON public.questions_bank FOR ALL USING (auth.role() = 'admin');

-- Seed some example courses (optional)
INSERT INTO public.mba_courses (name) VALUES
  ('Finance'),
  ('Marketing'),
  ('Data Science')
ON CONFLICT DO NOTHING;
