-- Migration: seed programs
INSERT INTO programs (name, slug) VALUES
  ('Master of Philosophy in Media & Digital Communication Management', 'master-of-philosophy-in-media-digital-communication-management'),
  ('Master of Philosophy in Information Systems', 'master-of-philosophy-in-information-systems'),
  ('Master of Philosophy in Leadership', 'master-of-philosophy-in-leadership'),
  ('Master of Philosophy in Management', 'master-of-philosophy-in-management'),
  ('Master of Philosophy in Finance', 'master-of-philosophy-in-finance'),
  ('Master of Philosophy in Accounting', 'master-of-philosophy-in-accounting'),
  ('Master of Philosophy in Marketing', 'master-of-philosophy-in-marketing'),
  ('Master of Philosophy in Applied Statistics', 'master-of-philosophy-in-applied-statistics'),
  ('Master of Arts in Peace, Security and Intelligence Management', 'master-of-arts-in-peace-security-and-intelligence-management'),
  ('Master of Arts in Brands and Communications Management', 'master-of-arts-in-brands-and-communications-management'),
  ('Master of Arts in Digital and Strategic Marketing Management', 'master-of-arts-in-digital-and-strategic-marketing-management'),
  ('Master of Arts in Media & Digital Communication Management', 'master-of-arts-in-media-digital-communication-management'),
  ('Master of Laws in Competition and Consumer Protection Law', 'master-of-laws-in-competition-and-consumer-protection-law'),
  ('Master of Laws in International Business and Commercial Law', 'master-of-laws-in-international-business-and-commercial-law'),
  ('Master of Laws in Natural Resources and Climate Change Law', 'master-of-laws-in-natural-resources-and-climate-change-law'),
  ('Master of Business Administration in Accounting & Finance', 'master-of-business-administration-in-accounting-finance'),
  ('Master of Business Administration in Auditing', 'master-of-business-administration-in-auditing'),
  ('Master of Business Administration in Internal Auditing', 'master-of-business-administration-in-internal-auditing'),
  ('Master of Business Administration in Corporate Governance', 'master-of-business-administration-in-corporate-governance'),
  ('Master of Business Administration in Marketing', 'master-of-business-administration-in-marketing'),
  ('Master of Business Administration in Total Quality Management', 'master-of-business-administration-in-total-quality-management'),
  ('Master of Business Administration in Corporate Communications', 'master-of-business-administration-in-corporate-communications'),
  ('Master of Business Administration in Petroleum Accounting & Finance', 'master-of-business-administration-in-petroleum-accounting-finance'),
  ('Master of Business Administration in Impact Entrepreneurship and Innovation', 'master-of-business-administration-in-impact-entrepreneurship-and-innovation'),
  ('Master of Business Administration in Business Management', 'master-of-business-administration-in-business-management'),
  ('Master of Business Administration in Wealth and Asset Management', 'master-of-business-administration-in-wealth-and-asset-management'),
  ('Master of Business Administration in Management Information Systems', 'master-of-business-administration-in-management-information-systems'),
  ('Master of Business Administration in Human Resource Management', 'master-of-business-administration-in-human-resource-management'),
  ('Master of Science in Insurance Risk Management', 'master-of-science-in-insurance-risk-management'),
  ('Master of Science in Procurement Management', 'master-of-science-in-procurement-management'),
  ('Master of Science in Pensions Management', 'master-of-science-in-pensions-management'),
  ('Master of Science in Information Systems', 'master-of-science-in-information-systems'),
  ('Master of Science in Leadership and Organizational Development', 'master-of-science-in-leadership-and-organizational-development'),
  ('Master of Science in Information Security Management', 'master-of-science-in-information-security-management'),
  ('Master of Science in Applied Statistics', 'master-of-science-in-applied-statistics'),
  ('Master of Science in Energy Economics and Finance', 'master-of-science-in-energy-economics-and-finance')
ON CONFLICT (slug) DO NOTHING;
