-- Supabase migration: create site_settings table
CREATE TABLE IF NOT EXISTS site_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT NOT NULL,
  value TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- RLS policies for admin role
CREATE POLICY "admin_select_site_settings" ON site_settings FOR SELECT USING (auth.role() = 'admin');
CREATE POLICY "admin_insert_site_settings" ON site_settings FOR INSERT WITH CHECK (auth.role() = 'admin');
CREATE POLICY "admin_update_site_settings" ON site_settings FOR UPDATE USING (auth.role() = 'admin') WITH CHECK (auth.role() = 'admin');
CREATE POLICY "admin_delete_site_settings" ON site_settings FOR DELETE USING (auth.role() = 'admin');
