-- Supabase migration: create events table
CREATE TABLE IF NOT EXISTS events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  start_dt TIMESTAMP WITH TIME ZONE NOT NULL,
  end_dt TIMESTAMP WITH TIME ZONE NOT NULL,
  cover_image_url TEXT,
  featured BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Enable RLS
ALTER TABLE events ENABLE ROW LEVEL SECURITY;

-- RLS policies for admin role
CREATE POLICY "admin_select_events" ON events FOR SELECT USING (auth.role() = 'admin');
CREATE POLICY "admin_insert_events" ON events FOR INSERT WITH CHECK (auth.role() = 'admin');
CREATE POLICY "admin_update_events" ON events FOR UPDATE USING (auth.role() = 'admin') WITH CHECK (auth.role() = 'admin');
CREATE POLICY "admin_delete_events" ON events FOR DELETE USING (auth.role() = 'admin');
