-- Supabase migration: create opportunities table
CREATE TABLE IF NOT EXISTS opportunities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  link TEXT,
  status TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- RLS policies for admin role
CREATE POLICY "admin_select_opportunities" ON opportunities FOR SELECT USING (auth.role() = 'admin');
CREATE POLICY "admin_insert_opportunities" ON opportunities FOR INSERT WITH CHECK (auth.role() = 'admin');
CREATE POLICY "admin_update_opportunities" ON opportunities FOR UPDATE USING (auth.role() = 'admin') WITH CHECK (auth.role() = 'admin');
CREATE POLICY "admin_delete_opportunities" ON opportunities FOR DELETE USING (auth.role() = 'admin');
