-- Supabase migration: create past_questions table
CREATE TABLE IF NOT EXISTS past_questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  programme TEXT NOT NULL,
  year INT NOT NULL,
  pdf_url TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- RLS policies for admin role
CREATE POLICY "admin_select_past_questions" ON past_questions FOR SELECT USING (auth.role() = 'admin');
CREATE POLICY "admin_insert_past_questions" ON past_questions FOR INSERT WITH CHECK (auth.role() = 'admin');
CREATE POLICY "admin_update_past_questions" ON past_questions FOR UPDATE USING (auth.role() = 'admin') WITH CHECK (auth.role() = 'admin');
CREATE POLICY "admin_delete_past_questions" ON past_questions FOR DELETE USING (auth.role() = 'admin');
