-- Supabase migration: create newsletter_subscribers table
CREATE TABLE IF NOT EXISTS newsletter_subscribers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- RLS policies for admin role
CREATE POLICY "admin_select_newsletter_subscribers" ON newsletter_subscribers FOR SELECT USING (auth.role() = 'admin');
CREATE POLICY "admin_insert_newsletter_subscribers" ON newsletter_subscribers FOR INSERT WITH CHECK (auth.role() = 'admin');
CREATE POLICY "admin_update_newsletter_subscribers" ON newsletter_subscribers FOR UPDATE USING (auth.role() = 'admin') WITH CHECK (auth.role() = 'admin');
CREATE POLICY "admin_delete_newsletter_subscribers" ON newsletter_subscribers FOR DELETE USING (auth.role() = 'admin');
