-- Supabase migration: create resources table
CREATE TABLE IF NOT EXISTS resources (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  url TEXT NOT NULL,
  thumbnail_url TEXT,
  "order" INT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- RLS policies for admin role
CREATE POLICY "admin_select_resources" ON resources FOR SELECT USING (auth.role() = 'admin');
CREATE POLICY "admin_insert_resources" ON resources FOR INSERT WITH CHECK (auth.role() = 'admin');
CREATE POLICY "admin_update_resources" ON resources FOR UPDATE USING (auth.role() = 'admin') WITH CHECK (auth.role() = 'admin');
CREATE POLICY "admin_delete_resources" ON resources FOR DELETE USING (auth.role() = 'admin');
