-- Supabase migration: create news table
CREATE TABLE IF NOT EXISTS news (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  content JSONB,
  cover_image_url TEXT,
  seo_title TEXT,
  seo_description TEXT,
  published_at TIMESTAMP WITH TIME ZONE,
  draft BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- RLS policies for admin role
CREATE POLICY "admin_select_news" ON news FOR SELECT USING (auth.role() = 'admin');
CREATE POLICY "admin_insert_news" ON news FOR INSERT WITH CHECK (auth.role() = 'admin');
CREATE POLICY "admin_update_news" ON news FOR UPDATE USING (auth.role() = 'admin') WITH CHECK (auth.role() = 'admin');
CREATE POLICY "admin_delete_news" ON news FOR DELETE USING (auth.role() = 'admin');
