-- Supabase migration: create executives table
CREATE TABLE IF NOT EXISTS executives (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  title TEXT,
  bio TEXT,
  photo_url TEXT,
  "order" INT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- RLS: allow only admin role to CRUD
CREATE POLICY "admin_select_executives" ON executives FOR SELECT USING (auth.role() = 'admin');
CREATE POLICY "admin_insert_executives" ON executives FOR INSERT WITH CHECK (auth.role() = 'admin');
CREATE POLICY "admin_update_executives" ON executives FOR UPDATE USING (auth.role() = 'admin') WITH CHECK (auth.role() = 'admin');
CREATE POLICY "admin_delete_executives" ON executives FOR DELETE USING (auth.role() = 'admin');
