-- Supabase migration: create chatbot_logs table
CREATE TABLE IF NOT EXISTS chatbot_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  message TEXT NOT NULL,
  response TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- RLS policies for admin role
CREATE POLICY "admin_select_chatbot_logs" ON chatbot_logs FOR SELECT USING (auth.role() = 'admin');
CREATE POLICY "admin_insert_chatbot_logs" ON chatbot_logs FOR INSERT WITH CHECK (auth.role() = 'admin');
CREATE POLICY "admin_update_chatbot_logs" ON chatbot_logs FOR UPDATE USING (auth.role() = 'admin') WITH CHECK (auth.role() = 'admin');
CREATE POLICY "admin_delete_chatbot_logs" ON chatbot_logs FOR DELETE USING (auth.role() = 'admin');
